FROM gg-summer.registry.jetbrains.space/p/p7/jajapy/base:latest


WORKDIR /base/jajapy
COPY requirements.txt dev_requirements.txt ./
RUN pip install -r requirements.txt -r dev_requirements.txt && \
    apt-get update && \ 
    apt-get install check -y && \
    rm -rf /var/lib/apt/lists/*

COPY . .

# Build SUDD
WORKDIR /base/jajapy/jajapy/SUDD
RUN make

# GO BACK
WORKDIR /base/jajapy
